table consulta_base
	lineageTag: 532c6af5-c767-40ce-bce4-f0005aa52559

	measure 'PPTO 2026 Base Acum' =
			VAR MesOrden = SELECTEDVALUE('cumplimiento_acumulado_2026_hasta_corte'[Mes Orden])
			VAR FechaCorte =
				IF(
					NOT ISBLANK(MesOrden),
					EOMONTH(DATE(2026, MesOrden, 1), 0)
				)
			RETURN
				IF(
					ISBLANK(MesOrden),
					BLANK(),
					CALCULATE(
						DIVIDE(SUM('consulta_base'[PPTO 26 Aprobado CLP]), 1000000000),
						FILTER(
							ALL('consulta_base'),
							VAR SegmentoNormalizado = LOWER(TRIM(COALESCE('consulta_base'[Segmento ], "")))
							VAR ProveedorNormalizado = LOWER(TRIM(COALESCE('consulta_base'[Proveedor], "")))
							VAR TipoGastoNormalizado = LOWER(TRIM(COALESCE('consulta_base'[Tipo de Gasto], "")))
							VAR EsBanco =
								SegmentoNormalizado IN {"banco chile", "banco perú", "banco peru"}
							VAR EsEccsa =
								SegmentoNormalizado = "retail chile"
									&& ProveedorNormalizado IN {"kyndryl spa", "kyndryl chile spa"}
							RETURN
								YEAR('consulta_base'[Mes/ Año]) = 2026
									&& 'consulta_base'[Mes/ Año] <= FechaCorte
									&& TipoGastoNormalizado IN {"capex", "opex"}
									&& (EsBanco || EsEccsa)
						)
					)
				)
		formatString: 0.0
		lineageTag: 4ab693b3-ade1-43db-b2b3-f4493d8afe13

	measure 'PPTO 2026 Tabla Acum' =
			VAR MesOrden = SELECTEDVALUE('cumplimiento_acumulado_2026_hasta_corte'[Mes Orden])
			RETURN
				IF(
					ISBLANK(MesOrden),
					BLANK(),
					CALCULATE(
						SUM('cumplimiento_acumulado_2026_hasta_corte'[PPTO 2026]),
						FILTER(
							ALL('cumplimiento_acumulado_2026_hasta_corte'),
							'cumplimiento_acumulado_2026_hasta_corte'[Mes Orden] = MesOrden
						)
					)
				)
		formatString: 0.0
		lineageTag: e826866a-8c68-4929-8e28-80b82d4630a4

	measure 'PPTO 2026 Diferencia Control' = [PPTO 2026 Base Acum] - [PPTO 2026 Tabla Acum]
		formatString: 0.0
		lineageTag: d8bb56aa-e52a-4584-bf5c-d10874544861

	measure 'REAL 2026 Base Acum' =
			VAR MesOrden = SELECTEDVALUE('cumplimiento_acumulado_2026_hasta_corte'[Mes Orden])
			VAR FechaCorte =
				IF(
					NOT ISBLANK(MesOrden),
					EOMONTH(DATE(2026, MesOrden, 1), 0)
				)
			RETURN
				IF(
					ISBLANK(MesOrden),
					BLANK(),
					CALCULATE(
						DIVIDE(SUM('consulta_base'[2026 REAL CLP]), 1000000000),
						FILTER(
							ALL('consulta_base'),
							VAR SegmentoNormalizado = LOWER(TRIM(COALESCE('consulta_base'[Segmento ], "")))
							VAR ProveedorNormalizado = LOWER(TRIM(COALESCE('consulta_base'[Proveedor], "")))
							VAR TipoGastoNormalizado = LOWER(TRIM(COALESCE('consulta_base'[Tipo de Gasto], "")))
							VAR EsBanco =
								SegmentoNormalizado IN {"banco chile", "banco perú", "banco peru"}
							VAR EsEccsa =
								SegmentoNormalizado = "retail chile"
									&& ProveedorNormalizado IN {"kyndryl spa", "kyndryl chile spa"}
							RETURN
								YEAR('consulta_base'[Mes/ Año]) = 2026
									&& 'consulta_base'[Mes/ Año] <= FechaCorte
									&& TipoGastoNormalizado IN {"capex", "opex"}
									&& (EsBanco || EsEccsa)
						)
					)
				)
		formatString: 0.0
		lineageTag: ffb6a96e-389b-4ae2-b1a5-1167a8c468dc

	measure 'REAL 2026 Tabla Acum' =
			VAR MesOrden = SELECTEDVALUE('cumplimiento_acumulado_2026_hasta_corte'[Mes Orden])
			RETURN
				IF(
					ISBLANK(MesOrden),
					BLANK(),
					CALCULATE(
						SUM('cumplimiento_acumulado_2026_hasta_corte'[REAL 2026]),
						FILTER(
							ALL('cumplimiento_acumulado_2026_hasta_corte'),
							'cumplimiento_acumulado_2026_hasta_corte'[Mes Orden] = MesOrden
						)
					)
				)
		formatString: 0.0
		lineageTag: 9ce317c9-f267-4c4c-847e-894203f371ca

	measure 'REAL 2026 Diferencia Control' = [REAL 2026 Base Acum] - [REAL 2026 Tabla Acum]
		formatString: 0.0
		lineageTag: 2e8bd71a-1ae0-4221-b8c3-4503ab935c49

	column País
		dataType: string
		lineageTag: 0c8cb76a-8f88-49cc-bf51-9c242dc1f785
		summarizeBy: none
		sourceColumn: País

		annotation SummarizationSetBy = Automatic

	column 'Segmento '
		dataType: string
		lineageTag: 119ed56b-f4e1-4442-a3aa-002e1883735e
		summarizeBy: none
		sourceColumn: "Segmento "

		annotation SummarizationSetBy = Automatic

	column 'Categoría Comité'
		dataType: string
		lineageTag: fb8f7ecb-501d-438d-ad83-60186a88efe3
		summarizeBy: none
		sourceColumn: Categoría Comité

		annotation SummarizationSetBy = Automatic

	column 'Direccionable Nuevo'
		dataType: string
		lineageTag: 329b991d-1403-4b9b-8b20-5ceba8dddbbc
		summarizeBy: none
		sourceColumn: Direccionable Nuevo

		annotation SummarizationSetBy = Automatic

	column Perimetro
		dataType: string
		lineageTag: 7de0d9e5-7557-4e17-8270-801127084be2
		summarizeBy: none
		sourceColumn: Perimetro

		annotation SummarizationSetBy = Automatic

	column 'AMS/ IMS'
		dataType: string
		lineageTag: a2d9ec20-d6f2-49a8-8083-98ea4eeee2ef
		summarizeBy: none
		sourceColumn: AMS/ IMS

		annotation SummarizationSetBy = Automatic

	column Torre
		dataType: string
		lineageTag: 872d9c42-2e69-4f9b-babb-46349716bc7c
		summarizeBy: none
		sourceColumn: Torre

		annotation SummarizationSetBy = Automatic

	column 'Gerencia 1° Linea'
		dataType: string
		lineageTag: d96c9f83-fc03-47a3-98d0-8ee5be4df7b1
		summarizeBy: none
		sourceColumn: Gerencia 1° Linea

		annotation SummarizationSetBy = Automatic

	column 'Gerencia 2° Linea'
		dataType: string
		lineageTag: ec70af17-a65e-48f7-b621-53a81cfdf619
		summarizeBy: none
		sourceColumn: Gerencia 2° Linea

		annotation SummarizationSetBy = Automatic

	column Proveedor
		dataType: string
		lineageTag: 86498abd-0952-4634-af59-0e6d1be204eb
		summarizeBy: none
		sourceColumn: Proveedor

		annotation SummarizationSetBy = Automatic

	column 'Moneda Contrato'
		dataType: string
		lineageTag: 4c5f8792-d1d3-4c6a-969b-95135a75edc6
		summarizeBy: none
		sourceColumn: Moneda Contrato

		annotation SummarizationSetBy = Automatic

	column 'Mes/ Año'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d525897b-8b30-4228-863a-bd94df640c0a
		summarizeBy: none
		sourceColumn: Mes/ Año

		variation Variación
			isDefault
			relationship: a11a7834-b59c-4313-93d8-f00471929fc9
			defaultHierarchy: LocalDateTable_73faddd3-3d2d-43a8-b2a6-e6bb10e0aca5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column '2025 REAL MO'
		dataType: double
		lineageTag: 74f48ba7-df5a-4cf4-a3c4-2e08a3e057fc
		summarizeBy: sum
		sourceColumn: 2025 REAL MO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '2026 FCST MO'
		dataType: double
		lineageTag: d9f7cd95-a4f0-42b6-8994-b45fc6409e75
		summarizeBy: sum
		sourceColumn: 2026 FCST MO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '2026 REAL MO'
		dataType: double
		lineageTag: c7476539-5b1a-43dd-80b1-13a2211aedbe
		summarizeBy: sum
		sourceColumn: 2026 REAL MO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PPTO 26 Aprobado MO'
		dataType: double
		lineageTag: cd51404c-c4d7-492f-a48b-c7a90a8a1486
		summarizeBy: sum
		sourceColumn: PPTO 26 Aprobado MO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '2025 REAL  CLP'
		dataType: double
		lineageTag: f1c2a37d-e6ec-4339-87d8-298b45c8a891
		summarizeBy: sum
		sourceColumn: 2025 REAL  CLP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '2026LB CLP'
		dataType: double
		lineageTag: 53a5155b-a442-4386-b345-40471bd56352
		summarizeBy: sum
		sourceColumn: 2026LB CLP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '2026 FCST CLP'
		dataType: double
		lineageTag: 86ea1069-2e03-4570-a53c-8966d284258e
		summarizeBy: sum
		sourceColumn: 2026 FCST CLP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '2026 REAL CLP'
		dataType: double
		lineageTag: c291dd7a-f97f-4111-83b8-4935e765cfba
		summarizeBy: sum
		sourceColumn: 2026 REAL CLP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PPTO 26 Aprobado CLP'
		dataType: double
		lineageTag: 9c005828-9bd9-40f7-a0c3-13251500aaa0
		summarizeBy: sum
		sourceColumn: PPTO 26 Aprobado CLP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tipo de Gasto'
		dataType: string
		lineageTag: db4df0be-54b4-409e-b9ee-ce636709db70
		summarizeBy: none
		sourceColumn: Tipo de Gasto

		annotation SummarizationSetBy = Automatic

	partition consulta_base = m
		mode: import
		source =
				let
				    Origen = SharePoint.Files("https://ripleycorp-my.sharepoint.com/personal/jnunezca_bancoripley_com_pe/", [ApiVersion = 15]),
				    #"Filas filtradas" = Table.SelectRows(Origen, each ([Extension] = ".xlsx")),
				    #"Gastos Consolidados (Vistas PPTO Steerco) xlsx_https://ripleycorp-my sharepoint com/personal/jnunezca_bancoripley_com_pe/Documents/Archivos de chat de Microsoft Teams/" = #"Filas filtradas"{[Name="Gastos Consolidados (Vistas PPTO Steerco).xlsx",#"Folder Path"="https://ripleycorp-my.sharepoint.com/personal/jnunezca_bancoripley_com_pe/Documents/Archivos de chat de Microsoft Teams/"]}[Content],
				    #"Libro de Excel importado" = Excel.Workbook(#"Gastos Consolidados (Vistas PPTO Steerco) xlsx_https://ripleycorp-my sharepoint com/personal/jnunezca_bancoripley_com_pe/Documents/Archivos de chat de Microsoft Teams/"),
				    #"Base Banco_Sheet" = #"Libro de Excel importado"{[Item="Base Banco",Kind="Sheet"]}[Data],
				    #"Filas superiores quitadas" = Table.Skip(#"Base Banco_Sheet",2),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Filas superiores quitadas", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"País", type text}, {"Segmento ", type text}, {"Segmento Contable", type text}, {"Cod Sociedad", Int64.Type}, {"Sociedad ", type text}, {"Categoría Comité", type text}, {"Categoría Corp", type text}, {"Direccionable Original ", type text}, {"Direccionable Nuevo", type text}, {"Perimetro", type text}, {"AMS/ IMS", type text}, {"Torre", type text}, {"Gerente Responsable ", type text}, {"TM/ PMO Responsable", type text}, {"Gerencia 1° Linea", type text}, {"Gerencia 2° Linea", type text}, {"Responsable Interno", type text}, {"Amortizado", type text}, {"Tipo de Gasto", type text}, {"Proveedor", type text}, {"Servicio", type text}, {"Cruce CDG", type text}, {"Numero Cuenta", type any}, {"Nombre Cuenta", type text}, {"Ceco", type text}, {"Gcia TI/ Otros", type text}, {"VST", type text}, {"Cód.Presupuesto", type text}, {"Cod PPTO Int", type text}, {"COD Identificador", type any}, {"Acreedor", type any}, {"Pago de Servicios", type text}, {"ID_Contrato", type text}, {"Fecha Inicio Contrato", type any}, {"Fecha Fin Contrato", type any}, {"Moneda Contrato", type text}, {"Afecta Impto.", type text}, {"Impto adi.", type text}, {"Mes/ Año", type date}, {"2025 LB MC", type text}, {"2025 PPTO MC", type number}, {"2025 REAL MC", Int64.Type}, {"2025 FCST MC", type number}, {"2026LB MC", type any}, {"2026 FCST MC", Int64.Type}, {"2026 REAL MC", type any}, {"2026 PPTO Aprobado MC", type any}, {"2025 LB MO", type any}, {"2025 PPTO MO", type number}, {"2025 REAL MO", Int64.Type}, {"2025 FCST MO", type number}, {"2026LB MO", type any}, {"2026 FCST MO", Int64.Type}, {"2026 REAL MO", type any}, {"PPTO 26 Aprobado MO", type any}, {"VB MO", type text}, {"2025 LB USD", type any}, {"2025 PPTO USD", type number}, {"2025 REAL USD", type number}, {"2025 FCST USD", type number}, {"2026LB USD", type text}, {"2026 FCST USD", Int64.Type}, {"2026 REAL USD", type any}, {"PPTO 26 Aprobado USD", type any}, {"2025 LB CLP", type text}, {"2025 PPTO CLP", type number}, {"2025 REAL  CLP", Int64.Type}, {"2025 FCST CLP", type number}, {"2026LB CLP", type text}, {"2026 FCST CLP", Int64.Type}, {"2026 REAL CLP", type any}, {"PPTO 26 Aprobado CLP", type text}, {"Tipo de OC planifiación", type any}, {"Comentarios", type text}, {"CRUCE", type text}}),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Tipo cambiado",{"País", "Segmento ", "Categoría Comité", "Direccionable Nuevo", "Perimetro", "AMS/ IMS", "Torre", "Gerencia 1° Linea", "Gerencia 2° Linea", "Tipo de Gasto", "Proveedor", "Moneda Contrato", "Mes/ Año", "2025 REAL MO", "2026 FCST MO", "2026 REAL MO", "PPTO 26 Aprobado MO", "2025 REAL  CLP", "2026LB CLP", "2026 FCST CLP", "2026 REAL CLP", "PPTO 26 Aprobado CLP"}),
				    #"Errores reemplazados" = Table.ReplaceErrorValues(#"Otras columnas quitadas", {{"Categoría Comité", null}}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Errores reemplazados",{{"2025 REAL MO", type number}, {"2026 FCST MO", type number}, {"2026 REAL MO", type number}, {"PPTO 26 Aprobado MO", type number}, {"2025 REAL  CLP", type number}, {"2026LB CLP", type number}, {"2026 FCST CLP", type number}, {"2026 REAL CLP", type number}, {"PPTO 26 Aprobado CLP", type number}}),
				    #"Errores reemplazados1" = Table.ReplaceErrorValues(#"Tipo cambiado1", {{"PPTO 26 Aprobado CLP", null}}),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Errores reemplazados1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Filas en blanco eliminadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table
