table visual_cumplimiento_anual_2026_Quantum
	isHidden
	lineageTag: a835e28e-dad8-4543-9be7-6d0f0e04d427

	measure 'Monto Cumplimiento Anual 2026 Quantum' = SUM('visual_cumplimiento_anual_2026_Quantum'[Monto])
		formatString: 0.0
		lineageTag: 92399534-160b-4266-9097-2c6dd307eaca

	column 'Métrica Orden'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 510319f6-4fb1-4c03-80ac-dedf89457d93
		summarizeBy: none
		sourceColumn: [Métrica Orden]

		annotation SummarizationSetBy = User

	column Métrica
		dataType: string
		lineageTag: 44e9b212-ad74-40dd-b5ce-cc4e53d1468d
		summarizeBy: none
		sourceColumn: [Métrica]
		sortByColumn: 'Métrica Orden'

		annotation SummarizationSetBy = User

	column 'Categoría Orden'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e4810d12-e26c-4e72-9097-f55d27f9213c
		summarizeBy: none
		sourceColumn: [Categoría Orden]

		annotation SummarizationSetBy = User

	column Categoría
		dataType: string
		lineageTag: d22547b8-9d0f-4c0c-a65c-4bb4e84327e6
		summarizeBy: none
		sourceColumn: [Categoría]
		sortByColumn: 'Categoría Orden'

		annotation SummarizationSetBy = User

	column Monto
		dataType: double
		formatString: 0.0
		lineageTag: 7395ff39-0307-4533-b1ee-2811ba231ca4
		summarizeBy: sum
		sourceColumn: [Monto]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition visual_cumplimiento_anual_2026_Quantum = calculated
		mode: import
		source =
				UNION(
					SELECTCOLUMNS(
						'cumplimiento_anual_2026_Quantum',
						"Métrica Orden", 1,
						"Métrica", "LB BC 26",
						"Categoría Orden", SWITCH('cumplimiento_anual_2026_Quantum'[Categoría], "Financiero", 2, "Eccsa", 1),
						"Categoría", IF('cumplimiento_anual_2026_Quantum'[Categoría] = "Financiero", "Financiero", 'cumplimiento_anual_2026_Quantum'[Categoría]),
						"Monto", 'cumplimiento_anual_2026_Quantum'[LB BC 26]
					),
					SELECTCOLUMNS(
						'cumplimiento_anual_2026_Quantum',
						"Métrica Orden", 2,
						"Métrica", "FCST 26",
						"Categoría Orden", SWITCH('cumplimiento_anual_2026_Quantum'[Categoría], "Financiero", 2, "Eccsa", 1),
						"Categoría", IF('cumplimiento_anual_2026_Quantum'[Categoría] = "Financiero", "Financiero", 'cumplimiento_anual_2026_Quantum'[Categoría]),
						"Monto", 'cumplimiento_anual_2026_Quantum'[FCST 2026]
					)
				)

