table visual_cumplimiento_anual_2026_Quantum_CL
	isHidden
	lineageTag: 829b1cc8-16e9-41d8-837f-1c625b38573f

	measure 'Monto Cumplimiento Anual 2026 Quantum CL' = SUM('visual_cumplimiento_anual_2026_Quantum_CL'[Monto])
		formatString: 0.0
		lineageTag: 906d1860-f0b2-4e76-8460-70a3900e8dd9

	column 'Métrica Orden'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a241067d-5b51-4996-a33c-ce477fe75693
		summarizeBy: none
		sourceColumn: [Métrica Orden]

		annotation SummarizationSetBy = User

	column Métrica
		dataType: string
		lineageTag: 5c828a62-c251-44ab-8319-075065b477c5
		summarizeBy: none
		sourceColumn: [Métrica]
		sortByColumn: 'Métrica Orden'

		annotation SummarizationSetBy = User

	column 'Categoría Orden'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a11ba323-1189-4e82-a217-61a0fe8820a8
		summarizeBy: none
		sourceColumn: [Categoría Orden]

		annotation SummarizationSetBy = User

	column Categoría
		dataType: string
		lineageTag: 2dbb89e9-488a-4bee-9cbe-9ff9bd9f9310
		summarizeBy: none
		sourceColumn: [Categoría]
		sortByColumn: 'Categoría Orden'

		annotation SummarizationSetBy = User

	column Monto
		dataType: double
		formatString: 0.0
		lineageTag: ccfde16e-9d8a-42fa-8596-a794f4d97f8b
		summarizeBy: sum
		sourceColumn: [Monto]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition visual_cumplimiento_anual_2026_Quantum_CL = calculated
		mode: import
		source =
				UNION(
					SELECTCOLUMNS(
						'cumplimiento_anual_2026_Quantum_CL',
						"Métrica Orden", 1,
						"Métrica", "LB BC 26",
						"Categoría Orden", SWITCH('cumplimiento_anual_2026_Quantum_CL'[Categoría], "Financiero", 2, "Eccsa", 1),
						"Categoría", IF('cumplimiento_anual_2026_Quantum_CL'[Categoría] = "Financiero", "Financiero", 'cumplimiento_anual_2026_Quantum_CL'[Categoría]),
						"Monto", 'cumplimiento_anual_2026_Quantum_CL'[LB BC 26]
					),
					SELECTCOLUMNS(
						'cumplimiento_anual_2026_Quantum_CL',
						"Métrica Orden", 2,
						"Métrica", "FCST 26",
						"Categoría Orden", SWITCH('cumplimiento_anual_2026_Quantum_CL'[Categoría], "Financiero", 2, "Eccsa", 1),
						"Categoría", IF('cumplimiento_anual_2026_Quantum_CL'[Categoría] = "Financiero", "Financiero", 'cumplimiento_anual_2026_Quantum_CL'[Categoría]),
						"Monto", 'cumplimiento_anual_2026_Quantum_CL'[FCST 2026]
					)
				)

