table visual_cumplimiento_acumulado_2026_corte_PE
	isHidden
	lineageTag: 2a8a2d7f-db37-4649-85aa-072c84a023a7

	measure 'Monto Cumplimiento Acumulado 2026 Corte PE' = SUM('visual_cumplimiento_acumulado_2026_corte_PE'[Monto])
		formatString: 0.0
		lineageTag: b78b5f15-eeba-4803-b7d7-2c04a9dfd06b

	column 'Métrica Orden'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4d5d03e3-6b2b-4157-a84a-695b64a475f4
		summarizeBy: none
		sourceColumn: [Métrica Orden]

		annotation SummarizationSetBy = User

	column Métrica
		dataType: string
		lineageTag: 5908fb65-a29c-4525-8ca4-4e95b788b7a7
		summarizeBy: none
		sourceColumn: [Métrica]
		sortByColumn: 'Métrica Orden'

		annotation SummarizationSetBy = User

	column 'Categoría Orden'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ee28529e-8671-4bc1-942a-bc55f630ec08
		summarizeBy: none
		sourceColumn: [Categoría Orden]

		annotation SummarizationSetBy = User

	column Categoría
		dataType: string
		lineageTag: 7ba00180-0e99-4615-b401-d61acd9fa825
		summarizeBy: none
		sourceColumn: [Categoría]
		sortByColumn: 'Categoría Orden'

		annotation SummarizationSetBy = User

	column Monto
		dataType: double
		formatString: 0.0
		lineageTag: b1a71441-6d13-4b37-b41a-bb564c652b3d
		summarizeBy: sum
		sourceColumn: [Monto]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition visual_cumplimiento_acumulado_2026_corte_PE = calculated
		mode: import
		source =
				UNION(
					SELECTCOLUMNS(
						'cumplimiento_acumulado_2026_corte_PE',
						"Métrica Orden", 1,
						"Métrica", "PPTO 26",
						"Categoría Orden", SWITCH('cumplimiento_acumulado_2026_corte_PE'[Categoría], "Capex", 3, "Opex", 2, "Eccsa", 1),
						"Categoría", 'cumplimiento_acumulado_2026_corte_PE'[Categoría],
						"Monto", 'cumplimiento_acumulado_2026_corte_PE'[PPTO 2026]
					),
					SELECTCOLUMNS(
						'cumplimiento_acumulado_2026_corte_PE',
						"Métrica Orden", 2,
						"Métrica", "REAL 26",
						"Categoría Orden", SWITCH('cumplimiento_acumulado_2026_corte_PE'[Categoría], "Capex", 3, "Opex", 2, "Eccsa", 1),
						"Categoría", 'cumplimiento_acumulado_2026_corte_PE'[Categoría],
						"Monto", 'cumplimiento_acumulado_2026_corte_PE'[REAL 2026]
					)
				)
